### ISSUE TITLE
Cannot set content of Item when user not logged in

### ISSUE THREAD

**Issue by maisen20** [blomstra/flarum-ext-search#10]
Hello, unfortunately I get in the browser console the following error when a guest visits the forum. Because of that error, there's an error message in the #flarum-loading-error container displayed.

Error message:
`Error: [ItemList] Cannot set content of Item. Key 'discussions' is not present.`

I assume the problem is that no discussions are loaded when the user isn't logged in. 

- Once the visitor is logged in, everything works.
- If i disable this extension everything works.

**Comment by luceos** [comment]
What is your permission "View forum (discussions and users)" like?

**Comment by maisen20** [comment]
My forum is closed and accessible only to users, so only users are allowed to see the discussions. Guests are not allowed to see anything.

**Comment by luceos** [comment]
Yeah so that is the issue. The search bar has no discussion key because the user isn't logged in and guests have no permission to see discussions.

**Comment by maisen20** [comment]
Well, but that's a problem. I'm sure I'm not the only one who only gives access to registered visitors. Can you please fix this?
