### ISSUE TITLE
ezimuel/ringphp[1.1.2, ..., 1.2.2] require react/promise ~2.0 -> found react/promise[v2.0.0, ..., v2.10.0] but the package is fixed to v3.0.0

### ISSUE THREAD

**Issue by Litalino** [blomstra/flarum-ext-search#14]
Problem 1
    - blomstra/search[0.0.1, ..., 0.1.17] require elasticsearch/elasticsearch 7.* -> satisfiable by elasticsearch/elasticsearch[v7.0.0, ..., v7.17.2].
    - elasticsearch/elasticsearch[v7.11.0, ..., v7.17.2] require ezimuel/ringphp ^1.1.2 -> satisfiable by ezimuel/ringphp[1.1.2, 1.2.0, 1.2.1, 1.2.2].
    - ezimuel/ringphp[1.1.2, ..., 1.2.2] require react/promise ~2.0 -> found react/promise[v2.0.0, ..., v2.10.0] but the package is fixed to v3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - elasticsearch/elasticsearch[v7.0.0, ..., v7.10.0] require php ^7.1 -> your php version (8.1.24) does not satisfy that requirement.
    - Root composer.json requires blomstra/search * -> satisfiable by blomstra/search[0.0.1, ..., 0.1.17].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by luceos** [comment]
Whoops. Did you try with -W?

Feel free to reopen if this issue persisted.
